apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-cli/0.4/git-cli.yaml

namespace: sonataflow-infra

patches:
- path: git-cli-patch.yaml
  target:
    kind: Task
    name: git-cli
