apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pipelinerun.yaml

namespace: sonataflow-infra

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - envs:
      - run.properties
    name: pipelinerun-properties
transformers:
  - replace-properties.yaml
