apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: replace-properties
replacements:
  - source:
      kind: ConfigMap
      name: pipelinerun-properties
      fieldPath: data.workflowId
    targets:
      - select:
          kind: PipelineRun
        fieldPaths:
          - spec.params.[name=workflowId].value
  - source:
      kind: ConfigMap
      name: pipelinerun-properties
      fieldPath: data.gitUrl
    targets:
      - select:
          kind: PipelineRun
        fieldPaths:
          - spec.params.[name=gitUrl].value
  - source:
      kind: ConfigMap
      name: pipelinerun-properties
      fieldPath: data.sshGitUrl
    targets:
      - select:
          kind: PipelineRun
        fieldPaths:
          - spec.params.[name=sshGitUrl].value
  - source:
      kind: ConfigMap
      name: pipelinerun-properties
      fieldPath: data.convertToFlat
    targets:
      - select:
          kind: PipelineRun
        fieldPaths:
          - spec.params.[name=convertToFlat].value
