apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: flattener
  namespace: sonataflow-infra
spec:
  workspaces:
    - name: workflow-source
  params:
    - name: workflowId
      description: The workflow ID from the repository
      type: string
    - name: convertToFlat
      description: Whether conversion to flat layout is needed or it's already flattened
      type: string
      default: "true"
  steps:
    - name: flatten
      image: registry.access.redhat.com/ubi9-minimal
      workingDir: $(workspaces.workflow-source.path)
      script: |
        echo "--pwd"
        pwd
        echo "--ls"
        ls
        echo "--ls /workspace/*"
        ls /workspace/*
        ROOT=/workspace/workflow
        TARGET=flat
        mkdir -p flat
        if [ "$(params.convertToFlat)" == "true" ]; then
          cp -r workflow/$(params.workflowId)/src/main/resources flat/$(params.workflowId)
        else
          cp -r workflow/$(params.workflowId) flat/$(params.workflowId)
        fi

        curl -L https://raw.githubusercontent.com/parodos-dev/serverless-workflows/main/pipeline/workflow-builder.Dockerfile -o flat/workflow-builder.Dockerfile

        echo "--ls /workspace"
        ls /workspace
        echo "--ls /workspace/*"
        ls /workspace/*
        echo "--ls -l flat"
        ls -l flat
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-manifests
  namespace: sonataflow-infra
spec:
  workspaces:
    - name: workflow-source
  params:
    - name: workflowId
      description: The workflow ID from the repository
      type: string
  steps:
    - name: build-manifests
      image: registry.access.redhat.com/ubi9-minimal
      workingDir: $(workspaces.workflow-source.path)/flat/$(params.workflowId)
      script: |
        echo "--pwd"
        pwd
        echo "--ls"
        ls
        curl -L https://github.com/rgolangh/kie-tools/releases/download/0.0.2/kn-workflow-linux-amd64 -o kn-workflow
        chmod +x kn-workflow
        echo "Installed kn-workflow"
        ./kn-workflow gen-manifest --namespace ""
        echo "--ls manifests"
        ls manifests
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-kustomize
  namespace: sonataflow-infra
spec:
  workspaces:
    - name: workflow-source
    - name: kustomize-template
    - name: workflow-kustomize
  params:
    - name: workflowId
      description: The workflow ID from the repository
      type: string
    - name: imageTag
      type: string
  steps:
    - name: build-kustomize
      image: registry.access.redhat.com/ubi9-minimal
      workingDir: $(workspaces.kustomize-template.path)
      script: |
        echo "--pwd"
        pwd
        echo "--ls"
        ls
        echo "--ls .."
        ls ..
        cp $(workspaces.workflow-source.path)/flat/$(params.workflowId)/manifests/* kustomize/base
        echo "--ls kustomize/base"
        ls kustomize/base
        microdnf install -y findutils && microdnf clean all
        ./updater.sh $(params.workflowId) $(params.imageTag)

        cp -R kustomize $(workspaces.workflow-kustomize.path)

        echo "--cat $(workspaces.workflow-kustomize.path)/kustomize/base/kustomization.yaml"
        cat $(workspaces.workflow-kustomize.path)/kustomize/base/kustomization.yaml
        echo "--ls $(workspaces.workflow-kustomize.path)/kustomize/base"
        ls $(workspaces.workflow-kustomize.path)/kustomize/base
---